version: '3.3'

services:
  db:
    image: postgres:13.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env

  weather_app:
    build: ../
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data: