version: '3.9'

services:
  db:
    image: postgres:13.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

  weather_app:
    build: ../
    command: sh -c "alembic upgrade head && python src/main.py"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env


volumes:
  postgres_data: