"""Database creation

Revision ID: 6bc7c1e78ad4
Revises: 
Create Date: 2023-05-18 13:00:01.812666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bc7c1e78ad4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('city', sa.String(), nullable=True),
                    sa.Column('temperature', sa.Float(), nullable=True),
                    sa.Column('humidity', sa.Float(), nullable=True),
                    sa.Column('wind_speed', sa.Float(), nullable=True),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather')
    # ### end Alembic commands ###
